PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Transforms:
- DecodeImage:
    img_mode: BGR
    channel_first: false
- DetResizeForTest: null
- NormalizeImage:
    scale: 1./255.
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    order: hwc
- ToCHWImage: null
- KeepKeys:
    keep_keys:
    - image
    - shape
